### ISSUE TITLE
How do you run this?

### ISSUE THREAD

**Issue by sfederici** [TurboWarp/scratch-vm#1]
Sorry, this is not an issue. I would really like to know how TurboWarp can be installed and run locally or on a web server. Every configuration you used, even specific to your installation, would be good enough for me. Thanks in advance.

**Comment by ghost** [comment]
I'll try to get a guide or something written by the end of today

**Comment by ghost** [comment]
https://github.com/TurboWarp/scratch-gui/wiki/Getting-Started should explain it

**Comment by sfederici** [comment]
> https://github.com/TurboWarp/scratch-gui/wiki/Getting-Started should explain it

Excellent! Sorry if I asked again in the other comment :)
