### ISSUE TITLE
wrong characters while using sandboxed extensions

### ISSUE THREAD

**Issue by HydroGest** [TurboWarp/scratch-vm#112]
### Expected Behavior

Load custom extensions from URLs, then show the characters correctly.

### Actual Behavior

The extension has need successfully loaded, but the Chinese characters could not display normally.

[![pSFH3RK.jpg](https://s1.ax1x.com/2023/01/04/pSFH3RK.jpg)](https://imgse.com/i/pSFH3RK)

### Steps to Reproduce

Load Custom Extensions. [Url](http://tw.mkc.icu/static/extensions/in_dev/多人游戏.js)

**Comment by GarboMuffin** [comment]
The VM supports CJK characters just fine:

<img width="270" alt="image" src="https://user-images.githubusercontent.com/33787854/213001514-5a82f80e-0d96-462d-b03d-4b9d53f58d40.png">

The most likely explanation is that the file was saved with the wrong encoding or the server is using the wrong encoding. It should be UTF-8

**Comment by GarboMuffin** [comment]
Turns out they were just broken in the sandbox. They will work in the next update.
