### ISSUE TITLE
Scratch Lab

### ISSUE THREAD

**Issue by samuellouf** [TurboWarp/scratch-vm#127]
First of all, this is not actually an issue.
I just wanted to share my thoughts about Scratch Lab.
Scratch Lab is awesome : It has animated text blocks, face sensing blocks, and contrast blocks.
But TurboWarp is more awesome : it has customs extensions, Turbo Mode...
Now, let's imagine that TurboWarp and Scratch Lab were combined :
![TurboWarp Lab Logo](https://github.com/samuellouf/samuellouf/blob/main/turbowarp-lab/costume1.png?raw=true)
We would get "TurboWarp Lab".
And I think it has something to do with the scratch-vm.
Have a look at this -> [scartch-vm extensions](https://github.com/TurboWarp/scratch-vm/tree/develop/src/extensions)
We could try to import the Scratch Lab extensions into the "basic" scratch-vm, mod the VM into TurboWarp, and we could have a "TurboWarp Lab".

**Comment by OeildeLynx31** [comment]
> We could try to import the Scratch Lab extensions into the "basic" scratch-vm, mod the VM into TurboWarp, and we could have a "TurboWarp Lab".

We can't, because the source code of Scratch Lab isn't shared.

**Comment by Mistium** [comment]
This would be very useful, we have access to the extensions themselves and ghandi ide has implemented a scratch labs extension system so i don't see why turbowarp can't implement that.

**Comment by Mistium** [comment]
https://cocrea.world/gandi

This scratch ide has scratch labs extensions that work

**Comment by GarboMuffin** [comment]
i've mentioned this elsewhere: Scratch Labs is, to my knowledge, still not available under an open source license. the only way they will be added is if someone reimplements them under an open source license.
