### ISSUE TITLE
Loading extensions through fetch or XHR rather than script tags

### ISSUE THREAD

**Issue by ZXMushroom63** [TurboWarp/scratch-vm#140]
Currently extensions are loaded via a script with an src. The problem with this is certain domains like raw.githubusercontent.com do not work.

An easy workaround would be loading them through fetch or XHR, like: 
`fetch(extension_url).then(res=>res.blob().then(blob=>blob.text().then(text=>{`
`console.log(text);`
`})))`

**Comment by GarboMuffin** [comment]
and loading them through fetch breaks even more sites, to be clear

**Comment by ZXMushroom63** [comment]
Maybe using XHR as a fallback would be a better idea?
<script onerror="loadViaOtherMethod()" src="something" ></script>

**Comment by GarboMuffin** [comment]
honestly, using fetch-first would probably not be a bad idea. with `new Function` we would get better error messages about syntax errors and worry less about leaking global variables

**Comment by GarboMuffin** [comment]
I reverted this. I think we actually just can't do this:

 - It *will* break projects
 - Stack traces from errors in extensions are unusable
