### ISSUE TITLE
Clipboard interaction

### ISSUE THREAD

**Issue by illogicalapple** [TurboWarp/scratch-vm#152]
I think it would be nice if you could interact with the clipboard via a custom block in TurboWarp. It already has support for backspace, control, etc., which makes it especially good for text editing in Scratch. I'm currently recreating the Password Game, which definitely requires at least paste (for the phase of the moon rule). I tried to PR myself but couldn't figure out the code :despair:

**Comment by LilyMakesThings** [comment]
You can use a TurboWarp extension. If you're asking for a block like 'is compiled?' or 'is TurboWarp?', those types of blocks are no longer being added

**Comment by CST1229** [comment]
> You can use a TurboWarp extension

(If you don't know, they're at [extensions.turbowarp.org](https://extensions.turbowarp.org).)
