### ISSUE TITLE
about util.ioQuery

### ISSUE THREAD

**Issue by qxsck** [TurboWarp/scratch-vm#153]
What is the 'util.ioQuery' of the 'getKeyPressed' function in 'scratch3_sensing.js'?

**Comment by GarboMuffin** [comment]
you can't run a block using an ioQuery. just copy and paste the code of getKeyPressed, it's not long

https://github.com/TurboWarp/scratch-vm/blob/develop/src/blocks/scratch3_sensing.js#L260

**Comment by GarboMuffin** [comment]
Oh, misunderstood I think. ioQuery is just a slightly less ugly way to run functions from runtime.ioDevices

**Comment by LilyMakesThings** [comment]
...even though, at least in my opinion, it is uglier
