### ISSUE TITLE
Upload To Scratch

### ISSUE THREAD

**Issue by alinco8** [TurboWarp/scratch-vm#162]
#### And I'm not used to using Github Issue, so sorry if it's hard to see.

Hello!!!
Using custom extensions will prevent uploading to Scratch, but how about converting features that are only available in Turbowarp to comments when compiling to .sb3, so that they can be uploaded to Scratch? Then when the project is loaded in Turbowarp, you can build from the comments and it will work as a comment in Scratch so you can upload it and Turbowarp can run it.

**Comment by alinco8** [comment]
## In TurboWarp
![img](https://github.com/TurboWarp/scratch-vm/assets/87509441/ed372e67-87e3-4d6b-916c-a6ba1122c806)
## In Scratch (Sprite)
![img1](https://github.com/TurboWarp/scratch-vm/assets/87509441/8ea40223-fa80-4ba0-9d74-7c333fcc2e53)
## In Scratch (Stage)
![img2](https://github.com/TurboWarp/scratch-vm/assets/87509441/789c0c39-a261-4ed8-8285-1891dd587a7e)

**Comment by alinco8** [comment]
If we can't upload to Scratch, we would have to set up our own server, which would make it difficult to advertise, etc. (and would make people wary because they would post links that are neither Scratch nor Turbowarp).

**Comment by LilyMakesThings** [comment]
share.turbowarp.org already exists

**Comment by alinco8** [comment]
I didn't know... Thanks! I knew GarboMuffin was the best!
