### ISSUE TITLE
Broadcasts get compiled dynamically

### ISSUE THREAD

**Issue by softedco** [TurboWarp/scratch-vm#166]
### Expected Behavior

Broadcasts should get compiled once after you click the green flag and the code doesn't change until you click the green flag again

### Actual Behavior

Changes in the code reflect on what's happening on the scene regardless of what the _Disable compiler_ setting says

### Steps to Reproduce

![image](https://github.com/TurboWarp/scratch-vm/assets/100989385/1d59942f-8ae2-4a1a-b6ae-c2dc74c2fa4e)

### Operating System and Browser

N/A

**Comment by CST1229** [comment]
Can't replicate, make sure you don't have the "Disable compiler in editor" addon on.
![image](https://github.com/TurboWarp/scratch-vm/assets/68464103/de7f5abe-9146-4d94-ab21-4eca85fadd9b)

**Comment by softedco** [comment]
I don't have it

**Comment by softedco** [comment]
oh wait wrong image
![image](https://github.com/TurboWarp/scratch-vm/assets/100989385/84fbd1dc-a999-4ab0-b6f3-29ab19910ee2)
it should be this

**Comment by CST1229** [comment]
> oh wait wrong image
![image](https://user-images.githubusercontent.com/100989385/271820207-84fbd1dc-a999-4ab0-b6f3-29ab19910ee2.png)
it should be this

Scripts are recompiled the next time they're run when they're modified, this is normal. (It happens with custom blocks, too.)

**Comment by softedco** [comment]
> > oh wait wrong image
> > ![image](https://user-images.githubusercontent.com/100989385/271820207-84fbd1dc-a999-4ab0-b6f3-29ab19910ee2.png)
> > it should be this
> 
> Scripts are recompiled the next time they're run when they're modified, this is normal. (It happens with custom blocks, too.)

it doesn't happen with custom blocks, it happens exclusively to event hat blocks including broadcasts which can't start projects by themselves, that's why I think they should be compiled only once because otherwise they ruin performance

**Comment by CST1229** [comment]
> it doesn't happen with custom blocks, it happens exclusively to event hat blocks including broadcasts which can't start projects by themselves, that's why I think they should be compiled only once because otherwise they ruin performance

They probably only get recompiled when they are modified (also yea custom blocks aren't counted as separate scripts, i probably got confused because i only really found it with custom blocks in broadcasts.).

**Comment by softedco** [comment]
> > it doesn't happen with custom blocks, it happens exclusively to event hat blocks including broadcasts which can't start projects by themselves, that's why I think they should be compiled only once because otherwise they ruin performance
> 
> They probably only get recompiled when they are modified (also yea custom blocks aren't counted as separate scripts, i probably got confused because i only really found it with custom blocks in broadcasts.).

they get recompiled each run because they are treated as event hat blocks and event hat blocks usually can start projects by themselves which broadcasts can't do

**Comment by GarboMuffin** [comment]
works as intended
