### ISSUE TITLE
Compile to GLSL shaders

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-vm#17]
It may be possible to compile a subset of Scratch blocks to GLSL shaders to run on GPU.

**Comment by pwouik** [comment]
to be fair that make no sense, the gpu is optimised for SIMD (running one code on large data), and cpu-gpu transfer are very expensive
unless you add an api to write shaders in scratch blocks, that you can use to directly render or compute a large volume of data
but even that would be very different from scratch, you only have 32bit scalars and fixed arrays

**Comment by GarboMuffin** [comment]
yeah it really doesn't make sense
