### ISSUE TITLE
Global blockUtility

### ISSUE THREAD

**Issue by veggiecan0419** [TurboWarp/scratch-vm#199]
Hi everyone,

**I had a question:**
How can I access the util (blockUtility) object outside a block definition?
(Like we can access the Scratch object outside of a block definition)

**Comment by LilyMakesThings** [comment]
it's literally just made up of functions from other places, made accessible there purely for convenience. 

you can read where it's pulling stuff from here: https://github.com/TurboWarp/scratch-vm/blob/develop/src/engine/block-utility.js

if you really cannot live without it, you can trap it by doing something like this.util = util.

**Comment by GarboMuffin** [comment]
Most of the functions on block utility are just one line things that call or set something on a thread that you would already need to have access to. There is one block utility object and it is shared by every block for performance reasons, so you would need to reinitialize the object yourself. Easier to just use the methods directly.

**Comment by veggiecan0419** [comment]
@LilyMakesThings 
> it's literally just made up of functions from other places, made accessible there purely for convenience.
> 
> you can read where it's pulling stuff from here: https://github.com/TurboWarp/scratch-vm/blob/develop/src/engine/block-utility.js

Thanks
You solved my problem!

**Comment by veggiecan0419** [comment]
@GarboMuffin 
You can mark the issue closed as planned as Lily answered my question
