### ISSUE TITLE
Custom reporters can hang browser in certain situations.

### ISSUE THREAD

**Issue by Wowfunhappy** [TurboWarp/scratch-vm#201]
I was testing some code when my browser tab completely froze. After some experimentation, I narrowed it down to the following minimal reproduction:

### Expected Behavior

This code should do nothing in both the interpreter and compiler.

![Screen Shot 2024-03-28 at 11 30 11 AM](https://github.com/TurboWarp/scratch-vm/assets/4484096/c85b633a-c9ad-4bb8-a672-b64d32fed059)

I've attached this code as an sb3 file: [turbowarp freeze.sb3.zip](https://github.com/TurboWarp/scratch-vm/files/14792119/turbowarp.freeze.sb3.zip)

### Actual Behavior

When the compiler is disabled and the above code is run, TurboWarp completely locks up! Pressing reload brings up a "page unresponsive" dialog in Chrome.

### Steps to Reproduce

The problem appears to occur any time the compiler is disabled and:

1. The result of a custom reporter is passed to another custom block as a parameter.
2. The second custom block reaches a `stop this script` or `return` block.

### Operating System and Browser

macOS, Chromium 121.

**Comment by GarboMuffin** [comment]
Looks like what's happening is frozen StackFrame state isn't being saved through thread.stopThisScript(). Same bug surfaces in vanilla Scratch in less-critical ways. Will try to get that fixed this weekend.

**Comment by Wowfunhappy** [comment]
Thank you!
