### ISSUE TITLE
Request: Allow unlimited cloud variables on unpackaged projects.

### ISSUE THREAD

**Issue by LIZARD-OFFICIAL** [TurboWarp/scratch-vm#211]
Please make cloud variables work the same on unpackaged projects opened in the website. When you package a project with 20 cloud variables, it works fine, but if you upload it to scratch and open it in turbowarp website, only 10 of them work. Why I need this is because I am working on a TruckersMP clone, but I realized people will cheat cause chaos on the game. With this feature, I could have a python server for moderation and save codes on first 10 variables, and the whole online thing on the other 10.

**Comment by CubesterYT** [comment]
You can't use unlimited cloud variables in Scratch. Scratch has a hard limit of 10 cloud variables, meaning any extra cloud variables are only supported on TurboWarp and packaged.

**Comment by LilyMakesThings** [comment]
It is literally hard-coded into the sb3 serialization that the limit is 10 in Scratch so this just fundamentally isn't possible.

**Comment by GarboMuffin** [comment]
If you want people to click on a link in the project description to play the project properly, there's no difference between that link being turbowarp.org/1234 or a link to a packaged version you host somewhere. Packaging it means you'll be able to use local storage cloud variables or extensions too.

**Comment by LIZARD-OFFICIAL** [comment]
> If you want people to click on a link in the project description to play the project properly, there's no difference between that link being turbowarp.org/1234 or a link to a packaged version you host somewhere. Packaging it means you'll be able to use local storage cloud variables or extensions too.

does that mean 20 vars will work?
