### ISSUE TITLE
Boolean procedure argument reporters from a different procedure with the same name as a number or string arugment act differently to Scratch

### ISSUE THREAD

**Issue by Tacodiva** [TurboWarp/scratch-vm#222]
TurboWarp seems to assume boolean input blocks always have a boolean value. This is not true in the case that the boolean procedure argument comes from a different procedure, but has the same name as a number or string argument in the current procedure. The following code behaves differently on Scratch and TurboWarp. In Scratch the boolean `foo` reporter reports the string "Haiii!", in Turbowarp it reports "true".

![image](https://github.com/user-attachments/assets/1fa681f2-680b-4239-8aa1-a34d17d9bbb9)

Demo Projects:
https://scratch.mit.edu/projects/1064784564/
https://turbowarp.org/1064784564/

**Comment by CubesterYT** [comment]
That's a weird compiler bug
