### ISSUE TITLE
Glow with compiler enabled

### ISSUE THREAD

**Issue by esawady** [TurboWarp/scratch-vm#35]
### Expected Behavior

<https://turbowarp.org/453148564/editor> works with compiler enabled

### Actual Behavior

Scripts do not glow if the compiler is enabled

### Steps to Reproduce

Go to <https://turbowarp.org/453148564/editor>, enable turbo mode, zoom out all the way (necessary due to an upstream performance issue), run. Note that the pixels do not glow. Disable compiler, note that pixels do glow. Shudder in horror at the abomination.

### Operating System and Browser

Linux, Chromium

### Notes

I'd be happy to write the necessary patch, though I'm not quite sure why this is happening - if you can give me some pointers to whereish you think the patch should be, I'll take a stab at this.

It's probably a good idea to make glow optional, it has some performance issues.

**Comment by GarboMuffin** [comment]
Script glowing is partially implemented now. See if this works for you: https://turbowarp.org/453148564/editor

**Comment by esawady** [comment]
Works, thanks!
