### ISSUE TITLE
Some ideas (useful and no)

### ISSUE THREAD

**Issue by aquaslvt** [TurboWarp/scratch-vm#41]
Hi GarboMuffin. I've made a favicon for TurboWarp ([here)](https://scratch.mit.edu/projects/474759939/) [ignore the thumbnail, and read the instructions.]

**Comment by aquaslvt** [comment]
1. *First issue comment*
2. Adding a "Login with Scratch" or "Login from Scratch" button for the cloud data. May impossible.
3. Adding an option that you choose if you want the **red theme** or the **dark theme**

``` javascript 
console.log("Bye-bye, " + user + "!");
```

**Comment by GarboMuffin** [comment]
Favicon is definitely long overdue at this point. Will look into finding something that I like.

Adding a login with Scratch button to access Scratch's cloud variable server is impossible without compromising account credentials.

Maybe there will be a dark mode toggle eventually.

**Comment by aquaslvt** [comment]
Thanks.
