### ISSUE TITLE
Support for Scratch lab stuff?

### ISSUE THREAD

**Issue by chunkybanana** [TurboWarp/scratch-vm#47]
There are a bunch of Turbowarp repos so I wasn't sure where to go. 

Scratch has released Scratch Lab with two new features. These will probably be improved and eventually added to normal Scratch. Should Turbowarp include these?

**Comment by GarboMuffin** [comment]
When they get added to LLK/scratch-vm, everything will *just work*. I'm most likely not going to add them before that point. They don't appear to be open source right now anyways.
