### ISSUE TITLE
Block "" = 0 returns false in scratch, but true in turbowarp.

### ISSUE THREAD

**Issue by Tacodiva** [TurboWarp/scratch-vm#50]
### Expected Behavior
![image](https://user-images.githubusercontent.com/27910867/109414716-694e5380-7a08-11eb-89de-0581325fb047.png)
This block should return false, as it does in scratch.

### Actual Behavior

This block returns true.

### Steps to Reproduce

See https://scratch.mit.edu/projects/494142821/
and http://turbowarp.org/494142821

### Operating System and Browser

Ubuntu 20.04.2 Google Chrome

**Comment by GarboMuffin** [comment]
thanks, should be fixed in next update
