### ISSUE TITLE
Debug Function to See Immediate Representation

### ISSUE THREAD

**Issue by 266-750Balloons** [TurboWarp/scratch-vm#67]
I know that you can view compiled Javascript in Turbowarp through vm.enableDebug(). I was wondering if there was a similar function to view the immediate representation generated by Turbowarp before it is compiled to Javascript?

**Comment by GarboMuffin** [comment]
Why do you want to look at it?

"Intermediate representation" is a really generous way to describe it as it's really just a slightly more abstract version of scratch-vm's AST. There's nothing very fancy or interesting in it. It really is just a tree.

**Comment by 266-750Balloons** [comment]
I'm just interested because I'm thinking about messing with my own compiler for fun. I want to see the output like how it comes out of irgen.js

**Comment by 266-750Balloons** [comment]
You know what, you're right. Now that I think of it, the json AST is sufficient. Thanks for your response.
