### ISSUE TITLE
Sync with scratch

### ISSUE THREAD

**Issue by nexensys** [TurboWarp/scratch-vm#68]
What do you think of allowing a user to sign into their scratch account and save a project that they are working on directly to their scratch account? You could add a "my stuff" page to let them select the projects and add a "save to scratch" button. I think it would be very useful so you don't have to edit-download-open scratch-upload every time you want to save a project to scratch. It would probably be a lot of work though.

**Comment by GarboMuffin** [comment]
We would need access to the user's Scratch account, which probably means we need their password to login as them. That's never happening. I think the ST would *very* much appreciate if mods don't become phishing sites.

**Comment by GarboMuffin** [comment]
Other option of making users install a browser extension is similarly not happening (not just because of Scratch's BE/USP)

**Comment by nexensys** [comment]
Ah ok. Sorry.
