### ISSUE TITLE
ScratchX Support?

### ISSUE THREAD

**Issue by Bloxem** [TurboWarp/scratch-vm#69]
Will The custom Addons support ScratchX Addons at some point?

ScratchX's addons also support JS

**Comment by GarboMuffin** [comment]
I initially wrote this off as being completely infeasible but I looked at some ScratchX extension source code out of curiosity and this could totally be possible for many of them

**Comment by GarboMuffin** [comment]
The development version of TurboWarp now has primitive support for some ScratchX extensions and loading ScratchX projects.

Some more documentation about this will be written later.

https://staging.turbowarp.org/editor?extension=https://ericrosenbaum.github.io/spotify-extension/extension.js&project_url=https://ericrosenbaum.github.io/spotify-extension/examples/dance-party.sbx
