### ISSUE TITLE
Idea: Autoload Trusted Custom Extensions

### ISSUE THREAD

**Issue by mguinhos** [TurboWarp/scratch-vm#70]
# Make turbowarp loads trusted unofficial extensions to speedup the code.

## Use cases
* parsing json
* displaying 3D graphics
* interpreters

## Requirements for trusted extensions
* must be in the trusted extensions repository
* must be able to be implemented using **vanilla** scratch

> **vanilla** means the default scratch runtime

## How the user should use:
![block](https://user-images.githubusercontent.com/43307018/141952978-5bf190bd-5301-442c-96fc-f2b76ad3aca4.png)

**Comment by poly2it** [comment]
No. This would make more sense as a third-party website rather than an implementation in the website. Importing single scripts is possible through .sprite3's.

**Comment by GarboMuffin** [comment]
This sortof exists now https://extensions.turbowarp.org/
