### ISSUE TITLE
Add a advanced option to disable sb3 optimizations

### ISSUE THREAD

**Issue by xAspirus** [TurboWarp/scratch-vm#75]
I'm working on a tool to make scratch projects more modular by separating code into different projects and merging them.
the sb3 optimizations make the block ids clash

anyone who uses my tool would also use this feature

**Comment by GarboMuffin** [comment]
Block ID collisions are already possible in regular Scratch regardless of TW's compression if someone tries to merge remixes. It could also happen if you just get really unlucky or your browser has broken RNG. Your tool should be handling this.
