### ISSUE TITLE
i was making a scratch extension and i got this error ReferenceError: vm is not defined

### ISSUE THREAD

**Issue by DemonLordDiablo** [TurboWarp/scratch-vm#77]
### Expected Behavior

should report the data of the variable you entered

### Actual Behavior

reports   ReferenceError: vm is not defined

### Steps to Reproduce

load the extension to turbowarp;
run the var[STRING] block;

full code at   https://jsfiddle.net/eapsc9y1/

i used https://onlineutf8tools.com/convert-utf8-to-data-uri to load the extension on turbowarp

### Operating System and Browser

_win 10 - chrome_

**Comment by GarboMuffin** [comment]
Custom extensions can not access the VM

You should consider forking scratch-gui, scratch-vm, etc.
