### ISSUE TITLE
question: Can you import a costume and assign it to a sprite in runtime?

### ISSUE THREAD

**Issue by TheShovel** [TurboWarp/scratch-vm#78]
Can you import a costume and assign it to a sprite in runtime using js? If yes, than how?

**Comment by GarboMuffin** [comment]
You can do whatever you want with JS but I don't understand what exactly you're trying to do

**Comment by TheShovel** [comment]
I wanna add a new costume from a link into a sprite, during runtime.

**Comment by GarboMuffin** [comment]
Here's something to get you started

```js
fetch("https://packager.turbowarp.org/assets/default-icon.290e09e569a1cab8e61ba93b0d23863f.png")
  .then((r) => r.arrayBuffer())
  .then((arrayBuffer) => {
    const storage = vm.runtime.storage;
    vm.addCostume("this part doesnt matter but the file extension does.png", {
      name: "abc",
      asset: new storage.Asset(
        storage.AssetType.ImageBitmap,
        null, // asset id, doesn't need to be set here because of `true` at the end will make Scratch generate it for you
        storage.DataFormat.PNG,
        new Uint8Array(arrayBuffer),
        true
      )
    })
  });
```

Costume is added to the sprite selected with vm.setEditingTarget. If you need more help, I'll just have to direct you to https://github.com/TurboWarp/scratch-vm/blob/develop/src/virtual-machine.js

**Comment by TheShovel** [comment]
Thanks a lot! But, for those who wanna use this, add ` vm.runtime.getSpriteTargetByName("sprite-name").id;` at the start of the code, so you edit the sprite you want to.
