### ISSUE TITLE
Wait block behaves differently

### ISSUE THREAD

**Issue by RexScratch** [TurboWarp/scratch-vm#8]
### Expected Behavior

The wait \_ seconds block should behave as it does in the official Scratch player.

### Actual Behavior

The wait \_ seconds block does not wait as long as it should.

### Steps to Reproduce

Run this project in both Scratch and TurboWarp: https://scratch.mit.edu/projects/416669082/

### Operating System and Browser

_Windows 10 2004 Edge 84.0.522.52_

**Comment by ghost** [comment]
Should be fixed now
