### ISSUE TITLE
Custom JavaScript

### ISSUE THREAD

**Issue by Virinas-code** [TurboWarp/scratch-vm#80]
### Feature Request
It would be great if we could run custom JavaScript code into a project. Making huge cloud projects requires more cloud backend than cloud variables, and if we had some custom JavaScript, we could make our own cloud engine, or have more features.

Even if it's not directly a block, it would be great having this as an extension (like the Debugger extension, which adds the `[ log ( ) ]` block).

There is already a similar block into [Snap!](https://snap.berkeley.edu).

### New blocks

- `( Run JavaScript ( input ) { ( code ) } )`
  - **Block type:** Reporter
  - **Parameters:**
    - *Value* __input__: The inputs to the custom JavaScript code. Fore more inout programmers may use lists.
    - *Value* __code__: JavaScript code to run, inside a function with inputs __inputs__, that are available through JS Variable __input__.
  - **Return value:** Return of the ran function.

### Example

`( Run JavaScript ( (x position) ) { ( "console.log(input); return input;" ) } )`

This code should run the following JavaScript code:

```javascript
var func = function customBlockFunction(input) {
    console.log(input);
    return input + 2;
};
return func();  // Reported value
```

So if the X position is 0, the reported value is 2 and there is a message "0" in the console.

### Security

With custom JS, people may use it to steal passwords, so if a project uses custom JS, it will show a big warning message, and there will be an *option* to enable JavaScript, that is not enabled by default.

###### I'm French sorry for my English

**Comment by GarboMuffin** [comment]
If you need custom JS, you are free to fork Scratch/TurboWarp, try custom extensions, or use the packager.

**Comment by Virinas-code** [comment]
OK, thank you. I'm going to use custom extensions, since I need an accessible cloud game that don't needs another logicial.

**Comment by DemonLordDiablo** [comment]
> ## #80 Running custom JavaScript code into program
> ### Feature Request
> It would be great if we could run custom JavaScript code into a project. Making huge cloud projects requires more cloud backend than cloud variables, and if we had some custom JavaScript, we could make our own cloud engine, or have more features.
> 
> Even if it's not directly a block, it would be great having this as an extension (like the Debugger extension, which adds the `[ log ( ) ]` block).
> 
> There is already a similar block into [Snap!](https://snap.berkeley.edu).
> 
> ### New blocks
> * `( Run JavaScript ( input ) { ( code ) } )`
>   
>   * **Block type:** Reporter
>   * **Parameters:**
>     
>     * _Value_ **input**: The inputs to the custom JavaScript code. Fore more inout programmers may use lists.
>     * _Value_ **code**: JavaScript code to run, inside a function with inputs **inputs**, that are available through JS Variable **input**.
>   * **Return value:** Return of the ran function.
> 
> ### Example
> `( Run JavaScript ( (x position) ) { ( "console.log(input); return input;" ) } )`
> 
> This code should run the following JavaScript code:
> 
> ```js
> var func = function customBlockFunction(input) {
>     console.log(input);
>     return input + 2;
> };
> return func();  // Reported value
> ```
> 
> So if the X position is 0, the reported value is 2 and there is a message "0" in the console.
> 
> ### Security
> With custom JS, people may use it to steal passwords, so if a project uses custom JS, it will show a big warning message, and there will be an _option_ to enable JavaScript, that is not enabled by default.
> 
> ###### Sorry if it's not clear, ask me for precision
> ###### I'm French sorry for my English

I've been working on a script to do things like that at : https://jsfiddle.net/rssa_romeo/cwrn8dxu/60/  if you want to check it out, only problem is that you would have to manually run it every time, or use an extension like ScriptAutoRunner to do it automatically.
