### ISSUE TITLE
vm.addSound returns Promise.reject for errors

### ISSUE THREAD

**Issue by TheShovel** [TurboWarp/scratch-vm#82]
`vm.addSound` returns `Promise.reject` for errors making it hard to find errors in code.

**Comment by TheShovel** [comment]
For example, 
`fetch("https://cataghg.github.io/kewlab-data/char%20edit.mp3")
  .then((r) => r.arrayBuffer())
  .then((arrayBuffer) => {
    const storage = vm.runtime.storage;
    vm.addSound("this part doesnt matter but the file extension does.mp3", {
      name: "abc",
      asset: new storage.Asset(
        storage.AssetType.Sound,
        null,
        storage.DataFormat.MP3,
        new Uint8Array(arrayBuffer),
        true
      )
    })
  });`
  
  returns a error, but I don't know why, and I want to fix it.

**Comment by GarboMuffin** [comment]
The error message is indeed exceptionally useless but you are using addSound wrong

https://github.com/TurboWarp/scratch-vm/blob/f8ec0084ade0038d23400abb4daba419cbdb2fa2/src/virtual-machine.js#L878-L884

```js
fetch("https://cataghg.github.io/kewlab-data/char%20edit.mp3")
  .then((r) => r.arrayBuffer())
  .then((arrayBuffer) => {
    const storage = vm.runtime.storage;
    const asset = new storage.Asset(
      storage.AssetType.Sound,
      null,
      storage.DataFormat.MP3,
      new Uint8Array(arrayBuffer),
      true
    );
    vm.addSound({
      md5: 'this part doesnt matter but the extension does.mp3',
      asset: asset,
      name: 'name'
    });
  });
```

Yes, the costume and sound APIs are inconsistent. That's just how it is.

**Comment by TheShovel** [comment]
Thanks! But the issue should be fixed because it's annoying.

**Comment by GarboMuffin** [comment]
There's an error in Scratch's addSound error handling. I have already fixed this in the latest update.
