### ISSUE TITLE
Questions About ScratchX Support

### ISSUE THREAD

**Issue by Samq64** [TurboWarp/scratch-vm#84]
I noticed ScratchX support was recently added. I have some questions bout it:

- Is ScratchX support experimental?
- Are ScratchX extensions loaded in the same way as the current extensions?
- Will this ever replace sandboxed extensions?
- Does ScratchX have any major restrictions?
- Can extensions be loaded from the ScratchX website?
- Does it work with the packager?

**Comment by GarboMuffin** [comment]
Don't get your hopes up too much. ScratchX extensions in TurboWarp have the same limitations as existing custom extensions (they both still run in the sandbox); all that was added is a shim to convert ScratchX APIs into Scratch 3 APIs.

It's still extremely primitive and experimental. A page will be added to docs.turbowarp.org when it's less experimental.

**Comment by Samq64** [comment]
Oh, okay, thanks.
