### ISSUE TITLE
"when timer > -1" doesn't work

### ISSUE THREAD

**Issue by FreeThrill** [TurboWarp/scratch-vm#86]
### Expected Behavior

"when timer > -1" should cause the script to run as soon as the project loads.

### Actual Behavior

it creates a bug in the console, and doesn't compile. This is bad because my project wants to check if you are on turbowarp as soon as the project loads, but turbowarp just bugs out.

### Steps to Reproduce

go to https://turbowarp.org/728386337 , open the console in inspect, and run the project.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by GarboMuffin** [comment]
The script won't be compiled (these types of blocks have additional complexity) but it will run the same as it would in Scratch

**Comment by GarboMuffin** [comment]
"is compiled?" still returns true even if the script failed to be compiled as long as the compiler is enabled in general.

**Comment by GarboMuffin** [comment]
"when timer > -1" works fine https://turbowarp.org/729708064/editor

What in that project indicates that it's not working fine?

**Comment by FreeThrill** [comment]
When I load the project, and then put this in the console:
```js
for (let target of vm.runtime.targets) {
  for (let variable of Object.values(target.variables)) {
    console.log(`${target.sprite.name}: ${variable.name} = ${variable.value}`);
  }
}
```
and scroll up to the _salt variable, it says "ithoughtitwasimpossible!". When I start the project and then do it, it changes to "thisvariableissecret". However, this was supposed to happen as soon as the project loaded since the scratch code looked like this:

function see_inside() {
     _salt = "thisvariableissecret";
}

when timer > 1 {
     if (is_turbowarp?) {
          see_inside;
     }
}

which shows that the script didn't start when the project loaded.

**Comment by GarboMuffin** [comment]
"when timer > -1" blocks don't run when the project is loaded, they run when the project is started, either by pressing the green flag or opening the editor. It works in Scratch the exact same.

By the way, if your system relies on see inside detectors to be secure, it will be trivial for people to "hack"
