### ISSUE TITLE
SuperWarp

### ISSUE THREAD

**Issue by PPPDUD** [TurboWarp/scratch-vm#88]
I suggest that you make a version of TurboWarp, called SuperWarp, which is like TurboWarp, but it doesn't try to have backwards compatibility with vanilla Scratch. Through this, we could be free of Scratch's strict limitations and have blocks like (ask for file of type (x)). Plus, a SuperWarp Packager would also be nice, so that we can distribute to our heart's content.

**Comment by PPPDUD** [comment]
Actually, PenguinMod is fixing this.

**Comment by GarboMuffin** [comment]
It is worth mentioning that the things described in https://github.com/TurboWarp/scratch-gui/issues/633 would make this possible in TurboWarp
